#!/usr/bin/env bash
# Script that transfers a file from our client to a server

file=$1
ip=$2
username=$3
key=$4

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$key" -o StrictHostKeyChecking=no "$file" "$username"@"$ip":
fi
