#!/usr/bin/env bash
# Install nginx on a server, listening on port 80
# When querying Nginx at its root with a GET request
# (requesting a page) using curl, it must return a page
# that contains the string Hello World

apt-get update -y
apt-get install nginx -y
chown ubuntu /var/www/html/index.nginx-debian.html
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx restart
