#!/usr/bin/env bash
# Install nginx on a server and configure it to have a custom 404 page

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo -e "Ceci n'est pas une page\n" > /var/www/html/page_404.html
sed -ie 's/server_name _;/server_name _;\n\terror_page 404 \/page_404.html;\n/' /etc/nginx/sites-available/default
service nginx restart
