#!/usr/bin/env bash
# Configure a Server

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo -e "Ceci n'est pas une page\n" > /var/www/html/page_404.html
sudo sed -ie 's/server_name _;/server_name _;\nerror_page 404 \/page_404.html;\n/' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a add_header X-Served-By $hostname;\n' /etc/nginx/sites-available/default
sudo service nginx restart
