#!/usr/bin/env bash
# Configure a Server

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/page_404.html
sudo sed -i '/server_name _;/a\ \terror_page 404 \/page_404.html;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a\ \tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
