#!/usr/bin/env bash
# Configure Nginx to running and listening on port 80
# of all the server's active IPv4 IPs

sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sed -i 's/listen [::]:80/listen [::]:80 default_server ipv6only=off;\n/' /etc/nginx/sites-enabled/default
sudo service nginx restart
