#!/usr/bin/env bash
# Run nginx as nginx user and add listening on port 8080

pkill apache2
chmod 777 /etc/nginx/nginx.conf
sed -i '/user www-data;/user nginx;' /etc/nginx/nginx.conf
sed -i '/80/8080' /etc/nginx/sites-available/default
service nginx start
